services:
  api:
    container_name: library_system_api
    build:
      context: .
      dockerfile: /Users/kacpersiembab/Projects/library_system/Dockerfile
    depends_on:
      - db
    ports:
      - "80:80"
    networks:
      - default
    
  db:
    container_name: library_system_db_compose
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: secret
    networks:
      - default
      
networks:
  default: {}