services:
  api:
    container_name: library_system_api
    build:
      context: .
      dockerfile: /Users/kacpersiembab/Projects/library_system/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "80:80"
    networks:
      - default
    
  db:
    container_name: library_system_db_compose
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: secret
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      
networks:
  default: {}